In [32]:
import sys
import os 

import pandas as pd
import numpy as np  

from bs4 import BeautifulSoup  
from selenium import webdriver  
from selenium.webdriver.common.keys import Keys
import chromedriver_autoinstaller

import time   
from tqdm import tqdm_notebook 

from selenium.webdriver.chrome.options import Options

import warnings
warnings.filterwarnings('ignore')

number_list = []
name_list = []

# pip install chromedriver_autoinstaller (없으면 깔아야함)
chrome_path = chromedriver_autoinstaller.install()


# Set up the options for headless browsing
chrome_options = Options()
# chrome_options.add_argument('--headless')
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--no-sandbox')

# Create a new instance of the Chrome driver with the options set
driver = webdriver.Chrome(chrome_path, chrome_options=chrome_options)

#season_set = [19]
#number_set = [1]

enternumber = [12, 18, 18, 16, 15]

#https://www.kovo.co.kr/game/v-league/11141_game-summary.asp?season=019&g_part=201&r_round=4&g_num=1&

for season in range(19, 20):
    print(season)
    for number in range(1, 2):
        sitename = f'https://www.kovo.co.kr/game/v-league/11141_game-summary.asp?season={season:03d}&g_part=201&r_round=1&g_num={number:d}&'

        print(sitename)

        driver.get(sitename)

        classname = "lst_board.lst_fixed.w123"
        table = driver.find_element_by_class_name(classname)

        # find the tbody element within the parent element
        thead_element = table.find_element_by_tag_name("thead")

        # find the tbody element within the parent element
        tbody_element = table.find_element_by_tag_name("tbody")

        # rows = tbody_element.find_elements_by_tag_name('td')

        rows = tbody_element.find_elements_by_tag_name('td')

        print(f'name')
        for ik, row in enumerate(rows):
            text = row.get_attribute('innerHTML')

            if '>'in text:
                text = text[text.find('>')+1:]
                text = text[:text.find('<')]
            
            print(text + ' ', end='')
            if ik % 2 == 1:
                print('')
                number_list.append(ik)
                name_list.append(text)

        print('')
        for i in range(5):
            globals()["data_list{}".format(i)] = []
            print(f'page number {i+1}')
            classname = f'lst_board.lst_scroll.w837.record_{i+1}'
            
            table = driver.find_element_by_class_name(classname)

            # find the tbody element within the parent element
            thead_element = table.find_element_by_tag_name("thead")


            # find the tbody element within the parent element
            tbody_element = table.find_element_by_tag_name("tbody")


            rows = tbody_element.find_elements_by_tag_name('td')
            
            data_temp = []

            for ik, row in enumerate(rows):
                text = row.get_attribute('innerHTML')
                    
                if '>'in text:
                    text = text[text.find('>')+1:]
                    text = text[:text.find('<')]
                print(text + ' ', end='')

                data_temp.append(text)
                
                if ik % enternumber[i] == enternumber[i]-1:
                    print('줄바꿈')
                    globals()["data_list{}".format(i)].append(data_temp)
                    # print(data_temp)
                    data_temp = []
            print('')



# Close the driver
driver.quit()

19
https://www.kovo.co.kr/game/v-league/11141_game-summary.asp?season=019&g_part=201&r_round=1&g_num=1&
name
18 링컨
10 정지석
23 김민재
1 김규민
9 곽승석
17 임동혁
2 한선수
14 오은렬
5 유광우
15 임재영 (OH)
16 정한용

page number 1
O O O O &nbsp; 19 34 19 1 2 55.88 38.64 줄바꿈
O O O O &nbsp; 12 18 9 1 1 50.00 20.45 줄바꿈
O O O O &nbsp; 10 8 7 0 0 87.50 9.09 줄바꿈
O O O O &nbsp; 10 7 6 0 0 85.71 7.95 줄바꿈
O O O O &nbsp; 7 13 7 1 0 53.85 14.77 줄바꿈
2  2  2  2  &nbsp; 7 7 6 0 0 85.71 7.95 줄바꿈
O O O O &nbsp; 3 1 1 0 0 100.00 1.14 줄바꿈
O O O O &nbsp; 0 0 0 0 0 0.00 0.00 줄바꿈
&nbsp; &nbsp; 18 18 &nbsp; 0 0 0 0 0 0.00 0.00 줄바꿈
1  1  &nbsp; &nbsp; &nbsp; 0 0 0 0 0 0.00 0.00 줄바꿈
9  9  9  1  &nbsp; 0 0 0 0 0 0.00 0.00 줄바꿈

page number 2
11 4 1 0 36.36 35.48 1 1 0 0 100.00 50.00 0 0 0 0 0.00 0.00 줄바꿈
12 6 1 0 50.00 38.71 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
5 3 1 0 60.00 16.13 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
2 2 0 0 100.00 6.45 1 1 0 0 100.00 50.00 0 0 0 0 0.00 0.00 줄바꿈
1 1 0 0 100.00 3.23 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈

page number 3
9 5 0 1 55.56 64.29 0 0 0 0 0.00 0.00 13 9 0 1 69.23 50.00 줄바꿈
2 1 0 0 50.00 14.29 0 0 0 0 0.00 0.00 4 2 0 1 50.00 15.38 줄바꿈
0 0 0 0 0.00 0.00 8 7 0 0 87.50 53.33 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 7 6 0 0 85.71 46.67 0 0 0 0 0.00 0.00 줄바꿈
3 3 0 0 100.00 21.43 0 0 0 0 0.00 0.00 5 1 0 0 20.00 19.23 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 4 3 0 0 75.00 15.38 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈
0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 0 0 0 0 0.00 0.00 줄바꿈

page number 4
8 0 4 0.00 8.16 6 5 1 0 1.25 11.32 4 0 1 0.00 4.49 줄바꿈
19 2 6 0.50 19.39 11 10 1 0 2.50 20.75 2 1 0 0.25 2.25 줄바꿈
14 0 2 0.00 14.29 2 1 0 1 0.25 3.77 1 1 0 0.25 1.12 줄바꿈
11 0 0 0.00 11.22 1 0 1 0 0.00 1.89 0 0 0 0.00 0.00 줄바꿈
15 0 5 0.00 15.31 14 10 4 0 2.50 26.42 3 1 0 0.25 3.37 줄바꿈
1 0 0 0.00 1.02 0 0 0 0 0.00 0.00 0 0 0 0.00 0.00 줄바꿈
20 0 1 0.00 20.41 8 5 3 0 1.25 15.09 68 40 1 10.00 76.40 줄바꿈
0 0 0 0.00 0.00 9 7 2 0 1.75 16.98 2 1 0 0.25 2.25 줄바꿈
2 0 0 0.00 2.04 1 1 0 0 0.50 1.89 9 7 0 3.50 10.11 줄바꿈
2 0 1 0.00 2.04 1 1 0 0 0.50 1.89 0 0 0 0.00 0.00 줄바꿈
6 0 0 0.00 6.12 0 0 0 0 0.00 0.00 0 0 0 0.00 0.00 줄바꿈

page number 5
0 0 0 0.00 0.00 7 0 3 3 0 0.00 12.73 1 0 7 줄바꿈
23 12 1 47.83 38.98 9 1 3 4 0 0.25 16.36 4 0 7 줄바꿈
0 0 0 0.00 0.00 13 3 3 5 1 0.75 23.64 1 0 4 줄바꿈
0 0 0 0.00 0.00 18 4 7 5 1 1.00 32.73 1 0 1 줄바꿈
20 7 0 35.00 33.90 3 0 1 0 1 0.00 5.45 1 0 6 줄바꿈
0 0 0 0.00 0.00 3 1 0 1 0 0.25 5.45 0 0 0 줄바꿈
0 0 0 0.00 0.00 2 2 0 0 0 0.50 3.64 0 0 2 줄바꿈
16 2 3 0.00 27.12 0 0 0 0 0 0.00 0.00 0 0 0 줄바꿈
0 0 0 0.00 0.00 0 0 0 0 0 0.00 0.00 0 0 0 줄바꿈
0 0 0 0.00 0.00 0 0 0 0 0 0.00 0.00 0 0 1 줄바꿈
0 0 0 0.00 0.00 0 0 0 0 0 0.00 0.00 0 0 0 줄바꿈

In [78]:
print(number_list, name_list)


list1 = ["시도",	"성공",	"공격차단",	"범실",	"성공률",	"점유율"]
list2 = ["시도",	"성공",	"공격차단",	"범실",	"성공률",	"점유율"]
list3 = ["시도",	"성공",	"공격차단",	"범실",	"성공률",	"점유율"]

print(len(data_list0))

# print(len(data_list0))
# print(len(data_list0[0]))


for b in range(len(data_list0[0])):
    globals()["temp_list{}".format(b)] = []
    for a in range(len(data_list0)):
        globals()["temp_list{}".format(b)].append(data_list0[a][b])

print(temp_list0)

df1 = pd.DataFrame({
    "번호" : number_list,
    "이름" : name_list,
    "1set" : temp_list0, 
    "2set" : temp_list1, 
    "3set" : temp_list2, 
    "4set" : temp_list3, 
    "5set" : temp_list4, 
    "득점" : temp_list5, 
    list1[0] : temp_list6, 
    list1[1] : temp_list7, 
    list1[2] : temp_list8, 
    list1[3] : temp_list9, 
    list1[4] : temp_list10, 
    list1[5] : temp_list11, 

})

for b in range(len(data_list1[0])):
    globals()["temp_list{}".format(b)] = []
    for a in range(len(data_list1)):
        globals()["temp_list{}".format(b)].append(data_list1[a][b])

df2 = pd.DataFrame({
    "오픈_" + list1[0] : temp_list0, 
    "오픈_" + list1[1] : temp_list1, 
    "오픈_" + list1[2] : temp_list2, 
    "오픈_" + list1[3] : temp_list3, 
    "오픈_" + list1[4] : temp_list4, 
    "오픈_" + list1[5] : temp_list5,
    "시간차_" + list2[0] : temp_list6, 
    "시간차_" + list2[1] : temp_list7, 
    "시간차_" + list2[2] : temp_list8, 
    "시간차_" + list2[3] : temp_list9, 
    "시간차_" + list2[4] : temp_list10, 
    "시간차_" + list2[5] : temp_list11,
    "이동_" + list3[0] : temp_list12, 
    "이동_" + list3[1] : temp_list13, 
    "이동_" + list3[2] : temp_list14, 
    "이동_" + list3[3] : temp_list15, 
    "이동_" + list3[4] : temp_list16, 
    "이동_" + list3[5] : temp_list17,
    
    
})

display(df1)
display(df2)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21] ['링컨', '정지석', '김민재', '김규민', '곽승석', '임동혁', '한선수', '오은렬', '유광우', '임재영 (OH)', '정한용']
11
['O', 'O', 'O', 'O', 'O', '2 ', 'O', 'O', '&nbsp;', '1 ', '9 ']

,오픈_시도,오픈_성공,오픈_공격차단,오픈_범실,오픈_성공률,오픈_점유율,시간차_시도,시간차_성공,시간차_공격차단,시간차_범실,시간차_성공률,시간차_점유율,이동_시도,이동_성공,이동_공격차단,이동_범실,이동_성공률,이동_점유율
0,11,4,1,0,36.36,35.48,1,1,0,0,100.00,50.00,0,0,0,0,0.00,0.00
1,12,6,1,0,50.00,38.71,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00
2,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00
3,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00
4,5,3,1,0,60.00,16.13,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00
5,2,2,0,0,100.00,6.45,1,1,0,0,100.00,50.00,0,0,0,0,0.00,0.00
6,1,1,0,0,100.00,3.23,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00
7,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00
8,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00
9,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00
10,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00,0,0,0,0,0.00,0.00