In [2]:
from fake_useragent import UserAgent
import pymysql
from openpyxl import Workbook
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import requests
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [5]:
# db 연결
db = pymysql.connect(host="localhost", port=3306, user="root", password="peter2012!", db="sba")
cursor = db.cursor()

# Excel 연결
wb = Workbook()
ws = wb.active

# webdriver 접속
release = 'https://chromedriver.storage.googleapis.com/LATEST_RELEASE'
version = requests.get(release).text
service = Service(ChromeDriverManager(version=version).install())
driver = webdriver.Chrome(service=service)

try:
    
    url = f"https://www.melon.com/chart/index.htm"
    driver.get(url)
    tbody = driver.find_elements(By.CSS_SELECTOR, "#frm > div > table > tbody > tr")

    for tr in tbody:
        rank = int(tr.find_element(By.CSS_SELECTOR, "span.rank").text.replace("'", '"'))
        title = tr.find_element(By.CSS_SELECTOR, "div.rank01 > span > a").text.replace("'", '"')
        singer = tr.find_element(By.CSS_SELECTOR, "div.ellipsis.rank02 > a").text.replace("'", '"')
        album = tr.find_element(By.CSS_SELECTOR, "div.rank03 > a").text.replace("'", '"')
        like = int(tr.find_element(By.CSS_SELECTOR, "button > span.cnt").text.replace(",", '').strip())
        
        diff = "new"
        try: 
            tr.find_element(By.CSS_SELECTOR, "span.rank_wrap > span.none")
            diff = "-"
        except: pass
        try:
            tr.find_element(By.CSS_SELECTOR, "span.rank_wrap > span.down")
            diff = "-"+tr.find_element(By.CSS_SELECTOR, "span.rank_wrap > span.down").text
        except: pass
        try:
            tr.find_element(By.CSS_SELECTOR, "span.rank_wrap > span.up")
            diff = "+"+tr.find_element(By.CSS_SELECTOR, "span.rank_wrap > span.up").text
        except: pass 
    
        sql = f"""
        INSERT INTO melon VALUES(NULL, '{rank}', '{title}', '{singer}', '{album}', '{like}', '{diff}', '00')
        """

        cursor.execute(sql)
        ws.append([rank, title, singer, album, like, diff, '00'])
        
except Exception as e:
    print(e)
finally:
    time.sleep(2)
    db.commit()
    db.close()
    driver.close()
    driver.quit()
    wb.save("melon.xlsx")

NewJeans
        INSERT INTO melon VALUES(NULL, '1', 'Super Shy', 'NewJeans', 'NewJeans 2nd EP "Get Up"', '116372', '-', '00')

정국
        INSERT INTO melon VALUES(NULL, '2', 'Seven (feat. Latto) - Clean Ver.', '정국', 'Seven (feat. Latto) - Clean Ver.', '125539', '-', '00')

NewJeans
        INSERT INTO melon VALUES(NULL, '3', 'ETA', 'NewJeans', 'NewJeans 2nd EP "Get Up"', '61060', '-', '00')

(여자)아이들
        INSERT INTO melon VALUES(NULL, '4', '퀸카 (Queencard)', '(여자)아이들', 'I feel', '125457', '-', '00')

IVE (아이브)
        INSERT INTO melon VALUES(NULL, '5', 'I AM', 'IVE (아이브)', 'I"ve IVE', '188974', '-', '00')

박재정
        INSERT INTO melon VALUES(NULL, '6', '헤어지자 말해요', '박재정', '1집 Alone', '96860', '-', '00')

LE SSERAFIM (르세라핌)
        INSERT INTO melon VALUES(NULL, '7', '이브, 프시케 그리고 푸른 수염의 아내', 'LE SSERAFIM (르세라핌)', 'UNFORGIVEN', '97015', '-', '00')

aespa
        INSERT INTO melon VALUES(NULL, '8', 'Spicy', 'aespa', 'MY WORLD - The 3rd Mini Album', '115502', '-', '00')

Lauv
        INSERT INTO melon VALUES(NULL, '9', 'Steal The Show (From “엘리멘탈”)', 'Lauv', 'Steal The Show (From “엘리멘탈”)', '109180', '-', '00')

NewJeans
        INSERT INTO melon VALUES(NULL, '10', 'New Jeans', 'NewJeans', 'NewJeans 2nd EP "Get Up"', '57598', '-', '00')

NewJeans
        INSERT INTO melon VALUES(NULL, '11', 'Hype boy', 'NewJeans', 'NewJeans 1st EP "New Jeans"', '275493', '-', '00')

IVE (아이브)
        INSERT INTO melon VALUES(NULL, '12', 'Kitsch', 'IVE (아이브)', 'I"ve IVE', '146022', '-', '00')

LE SSERAFIM (르세라핌)
        INSERT INTO melon VALUES(NULL, '13', 'UNFORGIVEN (feat. Nile Rodgers)', 'LE SSERAFIM (르세라핌)', 'UNFORGIVEN', '112567', '-', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '14', '사랑은 늘 도망가', '임영웅', '신사와 아가씨 OST Part.2', '201078', '-', '00')

NewJeans
        INSERT INTO melon VALUES(NULL, '15', 'Ditto', 'NewJeans', 'NewJeans "OMG"', '266527', '+1', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '16', '모래 알갱이', '임영웅', '모래 알갱이', '46171', '-1', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '17', '우리들의 블루스', '임영웅', 'IM HERO', '96825', '-', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '18', '다시 만날 수 있을까', '임영웅', 'IM HERO', '78772', '-', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '19', 'Candy', 'NCT DREAM', 'Candy - Winter Special Mini Album', '164685', '-', '00')

세븐틴 (SEVENTEEN)
        INSERT INTO melon VALUES(NULL, '20', '손오공', '세븐틴 (SEVENTEEN)', 'SEVENTEEN 10th Mini Album ‘FML"', '145192', '+2', '00')

NewJeans
        INSERT INTO melon VALUES(NULL, '21', 'Attention', 'NewJeans', 'NewJeans 1st EP "New Jeans"', '231330', '-1', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '22', '무지개', '임영웅', 'IM HERO', '67182', '-1', '00')

NewJeans
        INSERT INTO melon VALUES(NULL, '23', 'OMG', 'NewJeans', 'NewJeans "OMG"', '190254', '+1', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '24', '이제 나만 믿어요', '임영웅', '내일은 미스터트롯 우승자 특전곡', '170094', '-1', '00')

NewJeans
        INSERT INTO melon VALUES(NULL, '25', 'Cool With You', 'NewJeans', 'NewJeans 2nd EP "Get Up"', '31009', '+3', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '26', 'London Boy', '임영웅', 'Polaroid', '55121', '-1', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '27', 'Polaroid', '임영웅', 'Polaroid', '49907', '-1', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '28', 'ISTJ', 'NCT DREAM', 'ISTJ - The 3rd Album', '56633', '+1', '00')

지수 (JISOO)
        INSERT INTO melon VALUES(NULL, '29', '꽃', '지수 (JISOO)', 'ME', '117644', '+2', '00')

방탄소년단
        INSERT INTO melon VALUES(NULL, '30', 'Dynamite', '방탄소년단', 'Dynamite (DayTime Version)', '456890', '-', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '31', '아버지', '임영웅', 'IM HERO', '54945', '-4', '00')

IVE (아이브)
        INSERT INTO melon VALUES(NULL, '32', 'After LIKE', 'IVE (아이브)', 'After LIKE', '234092', '-', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '33', '인생찬가', '임영웅', 'IM HERO', '50927', '-', '00')

윤하 (YOUNHA)
        INSERT INTO melon VALUES(NULL, '34', '사건의 지평선', '윤하 (YOUNHA)', 'YOUNHA 6th Album Repackage "END THEORY : Final Edition"', '309519', '+4', '00')

IVE (아이브)
        INSERT INTO melon VALUES(NULL, '35', 'LOVE DIVE', 'IVE (아이브)', 'LOVE DIVE', '240661', '+1', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '36', 'A bientot', '임영웅', 'IM HERO', '52146', '-2', '00')

정국
        INSERT INTO melon VALUES(NULL, '37', 'Still With You', '정국', 'Still With You', '77833', '-', '00')

Charlie Puth
        INSERT INTO melon VALUES(NULL, '38', 'I Don"t Think That I Like Her', 'Charlie Puth', 'CHARLIE', '179860', '+2', '00')

방탄소년단
        INSERT INTO melon VALUES(NULL, '39', 'Butter', '방탄소년단', 'Butter', '291559', '+2', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '40', '손이 참 곱던 그대', '임영웅', 'IM HERO', '49918', '-5', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '41', '사랑해 진짜', '임영웅', 'IM HERO', '51083', '-2', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '42', '연애편지', '임영웅', 'IM HERO', '49047', '-', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '43', 'Broken Melodies', 'NCT DREAM', 'ISTJ - The 3rd Album', '68021', '-', '00')

부석순 (SEVENTEEN)
        INSERT INTO melon VALUES(NULL, '44', '파이팅 해야지 (Feat. 이영지)', '부석순 (SEVENTEEN)', '부석순 1st Single Album "SECOND WIND"', '167768', '-', '00')

Charlie Puth
        INSERT INTO melon VALUES(NULL, '45', 'Dangerously', 'Charlie Puth', 'Nine Track Mind (Deluxe Edition)', '187336', '-', '00')

FIFTY FIFTY
        INSERT INTO melon VALUES(NULL, '46', 'Cupid', 'FIFTY FIFTY', 'The Beginning: Cupid', '113062', '+1', '00')

STAYC(스테이씨)
        INSERT INTO melon VALUES(NULL, '47', 'Teddy Bear', 'STAYC(스테이씨)', 'Teddy Bear', '99983', '+1', '00')

방탄소년단
        INSERT INTO melon VALUES(NULL, '48', '봄날', '방탄소년단', 'YOU NEVER WALK ALONE', '549078', '+1', '00')

방탄소년단
        INSERT INTO melon VALUES(NULL, '49', 'Permission to Dance', '방탄소년단', 'Butter / Permission to Dance', '227325', '+5', '00')

임영웅
        INSERT INTO melon VALUES(NULL, '50', '보금자리', '임영웅', 'IM HERO', '48464', '-4', '00')

Agust D
        INSERT INTO melon VALUES(NULL, '51', '사람 Pt.2 (feat. 아이유)', 'Agust D', 'D-DAY', '74128', '+1', '00')

지민
        INSERT INTO melon VALUES(NULL, '52', 'Like Crazy', '지민', 'FACE', '66404', '-2', '00')

정국
        INSERT INTO melon VALUES(NULL, '53', 'Dreamers [Music from the FIFA World Cup Qatar 2022 Official Soundtrack] (Feat. FIFA Sound)', '정국', 'Dreamers [Music from the FIFA World Cup Qatar 2022 Official Soundtrack]', '126366', '+2', '00')

DK(디셈버)
        INSERT INTO melon VALUES(NULL, '54', '심(心)', 'DK(디셈버)', '심(心)', '57816', '-1', '00')

방탄소년단
        INSERT INTO melon VALUES(NULL, '55', 'Take Two', '방탄소년단', 'Take Two', '64605', '-4', '00')

LE SSERAFIM (르세라핌)
        INSERT INTO melon VALUES(NULL, '56', 'ANTIFRAGILE', 'LE SSERAFIM (르세라핌)', 'ANTIFRAGILE', '166780', '-', '00')

Paul Blanco
        INSERT INTO melon VALUES(NULL, '57', 'Summer (Feat. BE’O (비오))', 'Paul Blanco', 'Summer', '90048', '+2', '00')

NewJeans
        INSERT INTO melon VALUES(NULL, '58', 'ASAP', 'NewJeans', 'NewJeans 2nd EP "Get Up"', '27995', '-', '00')

H1-KEY (하이키)
        INSERT INTO melon VALUES(NULL, '59', '건물 사이에 피어난 장미 (Rose Blossom)', 'H1-KEY (하이키)', 'H1-KEY 1st Mini Album [Rose Blossom]', '85210', '+2', '00')

멜로망스
        INSERT INTO melon VALUES(NULL, '60', '사랑인가 봐', '멜로망스', '사랑인가 봐 (사내맞선 OST 스페셜 트랙)', '191182', '+2', '00')

임한별
        INSERT INTO melon VALUES(NULL, '61', '사랑하지 않아서 그랬어', '임한별', '사랑하지 않아서 그랬어', '34309', '-1', '00')

허각
        INSERT INTO melon VALUES(NULL, '62', '물론', '허각', '물론', '36390', '-5', '00')

(여자)아이들
        INSERT INTO melon VALUES(NULL, '63', 'Allergy', '(여자)아이들', 'I feel', '60446', '-', '00')

ZEROBASEONE (제로베이스원)
        INSERT INTO melon VALUES(NULL, '64', 'In Bloom', 'ZEROBASEONE (제로베이스원)', 'YOUTH IN THE SHADE', '49676', '-', '00')

성시경
        INSERT INTO melon VALUES(NULL, '65', '너의 모든 순간', '성시경', '별에서 온 그대 OST Part.7', '270657', '+2', '00')

우디 (Woody)
        INSERT INTO melon VALUES(NULL, '66', '사막에서 꽃을 피우듯', '우디 (Woody)', '사막에서 꽃을 피우듯', '15309', '-1', '00')

방탄소년단
        INSERT INTO melon VALUES(NULL, '67', 'The Planet', '방탄소년단', 'The Planet', '42460', '-1', '00')

이무진
        INSERT INTO melon VALUES(NULL, '68', '잠깐 시간 될까', '이무진', '잠깐 시간 될까', '49411', '+1', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '69', '파랑 (Blue Wave)', 'NCT DREAM', 'ISTJ - The 3rd Album', '35083', '-1', '00')

탑현
        INSERT INTO melon VALUES(NULL, '70', '나에게 그대만이', '탑현', '나에게 그대만이', '26993', '-', '00')

The Kid LAROI
        INSERT INTO melon VALUES(NULL, '71', 'STAY', 'The Kid LAROI', 'Stay', '268479', '+1', '00')

지아
        INSERT INTO melon VALUES(NULL, '72', '사랑..그게 뭔데', '지아', '사랑..그게 뭔데', '23139', '+1', '00')

j-hope
        INSERT INTO melon VALUES(NULL, '73', 'on the street (with J. Cole)', 'j-hope', 'on the street (with J. Cole)', '56081', '-2', '00')

(여자)아이들
        INSERT INTO melon VALUES(NULL, '74', 'TOMBOY', '(여자)아이들', 'I NEVER DIE', '240655', '+2', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '75', 'Like We Just Met', 'NCT DREAM', 'ISTJ - The 3rd Album', '37115', '-1', '00')

김민석 (멜로망스)
        INSERT INTO melon VALUES(NULL, '76', '취중고백', '김민석 (멜로망스)', '취중고백', '170790', '+2', '00')

임재현
        INSERT INTO melon VALUES(NULL, '77', 'Heaven(2023)', '임재현', '시작은 첫키스 OST Part.1', '32190', '-', '00')

경서
        INSERT INTO melon VALUES(NULL, '78', '첫 키스에 내 심장은 120BPM', '경서', 'ONGOING', '25123', '+1', '00')

Charlie Puth
        INSERT INTO melon VALUES(NULL, '79', 'That"s Hilarious', 'Charlie Puth', 'CHARLIE', '170788', '+1', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '80', 'Yogurt Shake', 'NCT DREAM', 'ISTJ - The 3rd Album', '33678', '-5', '00')

imase
        INSERT INTO melon VALUES(NULL, '81', 'NIGHT DANCER', 'imase', 'NIGHT DANCER', '112819', '+1', '00')

던 (DAWN)
        INSERT INTO melon VALUES(NULL, '82', '빛이 나는 너에게', '던 (DAWN)', '빛이 나는 너에게', '70063', '+1', '00')

#안녕
        INSERT INTO melon VALUES(NULL, '83', '해요 (2022)', '#안녕', '해요 (2022)', '85043', '+3', '00')

(여자)아이들
        INSERT INTO melon VALUES(NULL, '84', 'Nxde', '(여자)아이들', 'I love', '162242', '-', '00')

EXO
        INSERT INTO melon VALUES(NULL, '85', 'Cream Soda', 'EXO', 'EXIST - The 7th Album', '56300', '-4', '00')

케이시 (Kassy)
        INSERT INTO melon VALUES(NULL, '86', '사실말야내가말야그게그러니까말이야', '케이시 (Kassy)', '사실말야내가말야그게그러니까말이야', '22984', '+1', '00')

Charlie Puth
        INSERT INTO melon VALUES(NULL, '87', 'That’s Not How This Works (feat. Dan + Shay)', 'Charlie Puth', 'That’s Not How This Works (feat. Dan + Shay)', '65665', '+1', '00')

NewJeans
        INSERT INTO melon VALUES(NULL, '88', 'Get Up', 'NewJeans', 'NewJeans 2nd EP "Get Up"', '22152', '+2', '00')

김호중
        INSERT INTO melon VALUES(NULL, '89', '그중에 그대를 만나', '김호중', '삼남매가 용감하게 OST Part.1', '21366', '-4', '00')

경서예지
        INSERT INTO melon VALUES(NULL, '90', '다정히 내 이름을 부르면', '경서예지', '다정히 내 이름을 부르면 (경서예지 x 전건호)', '174816', '+2', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '91', 'Poison (모래성)', 'NCT DREAM', 'ISTJ - The 3rd Album', '30836', '-2', '00')

오마이걸 (OH MY GIRL)
        INSERT INTO melon VALUES(NULL, '92', '여름이 들려 (Summer Comes)', '오마이걸 (OH MY GIRL)', 'Golden Hourglass', '14291', '+1', '00')

테이
        INSERT INTO melon VALUES(NULL, '93', 'Monologue', '테이', 'Monologue', '88570', '+2', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '94', 'Skateboard', 'NCT DREAM', 'ISTJ - The 3rd Album', '29054', '-3', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '95', 'SOS', 'NCT DREAM', 'ISTJ - The 3rd Album', '29184', '-1', '00')

이채연
        INSERT INTO melon VALUES(NULL, '96', 'KNOCK', '이채연', 'Over The Moon', '39359', '+1', '00')

aespa
        INSERT INTO melon VALUES(NULL, '97', 'Thirsty', 'aespa', 'MY WORLD - The 3rd Mini Album', '58639', '+2', '00')

제이세라
        INSERT INTO melon VALUES(NULL, '98', '사랑의 바보', '제이세라', '사랑의 바보', '12669', '+2', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '99', 'Pretzel (♡)', 'NCT DREAM', 'ISTJ - The 3rd Album', '28272', '-3', '00')

NCT DREAM
        INSERT INTO melon VALUES(NULL, '100', '제자리 걸음 (Starry Night)', 'NCT DREAM', 'ISTJ - The 3rd Album', '28293', '-2', '00')

In [ ]:
#             sql = f"""
#             INSERT INTO melon VALUES(NULL, '{rank}', '{title}', '{singer}', '{album}', 0, '{diff}', '{str(time).zfill(2)}')
#             """
#             cursor.execute(sql)
#             ws.append([rank, title, singer, album, 0, diff, str(time).zfill(2)])